#!/usr/bin/env bash
echo 'vagrant  ALL= (ALL:ALL) NOPASSWD: ALL' >> /etc/sudoers

apt-get update -y
apt-get install htop -y
apt-get install linux-image-extra-`uname -r` -y

apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9

echo deb http://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list

apt-get update -y
apt-get install lxc-docker -y
apt-get install curl -y

curl -L https://github.com/orchardup/fig/releases/download/0.4.0/linux > /usr/local/bin/fig
chmod +x /usr/local/bin/fig