#!/usr/bin/env bash
cd /vagrant

# Stop and remove all containers
script/vagrant/docker_clean

# login to docker index
script/vagrant/docker_login

# build the project container
docker build --tag=web .
